import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { MainRoutingModule } from './main-routing.module';
import { MainComponent } from './main.component';

import { ThemeModule } from '../@theme/theme.module';
import { SharedModule } from '../@shared/shared.module';
import {
  HomeComponent,
  BookmarkComponent,
  CountryComponent,
  CountryListComponent,
  CollectionComponent,
  CollectionStoriesTabComponent,
  CollectionExperiencesTabComponent,
  CollectionAllComponent,
  JourneyComponent,
  JourneyInfoComponent,
  JourneyStoryComponent,
  WeekendOfGoodComponent,
  MeetComponent,
  SearchComponent,
  PrivacyPolicyComponent,
  TermsAndConditionsComponent,
  FAQComponent,
  ExperienceComponent,
  TestComponent,
  HomeForumComponent,
  StoryForumComponent,
  ScheduleComponent,
  ScheduleSingleComponent,
  TipsListComponent,
  BookmarkRecentlyComponent,
  BookmarkDetailComponent,
  BookmarkDetailExperienceComponent,
  BookmarkDetailStoryComponent,
  BookmarkListComponent,
  ContributorsComponent,
  RelatedStoriesComponent,
  RelatedStoriesCustomComponent,
  CountryForumComponent,
  StoryAmenitiesComponent,
  StoryInfoComponent,
  StoryHostComponent,
  StoryTravellverNoteComponent,
  NotFoundComponent,
  ForbiddenErrorComponent,
  DifferenceYouMakeComponent,
  TravellerManifestoComponent
} from './views';

@NgModule({
  declarations: [
    MainComponent,
    HomeComponent,
    BookmarkComponent,
    CountryComponent,
    CountryListComponent,
    CollectionComponent,
    CollectionStoriesTabComponent,
    CollectionExperiencesTabComponent,
    CollectionAllComponent,
    JourneyComponent,
    JourneyInfoComponent,
    JourneyStoryComponent,
    WeekendOfGoodComponent,
    MeetComponent,
    SearchComponent,
    PrivacyPolicyComponent,
    TermsAndConditionsComponent,
    FAQComponent,
    ExperienceComponent,
    TestComponent,
    HomeForumComponent,
    StoryForumComponent,
    ScheduleComponent,
    ScheduleSingleComponent,
    TipsListComponent,
    BookmarkRecentlyComponent,
    BookmarkDetailComponent,
    BookmarkDetailExperienceComponent,
    BookmarkDetailStoryComponent,
    BookmarkListComponent,
    ContributorsComponent,
    RelatedStoriesComponent,
    RelatedStoriesCustomComponent,
    CountryForumComponent,
    StoryAmenitiesComponent,
    StoryInfoComponent,
    StoryHostComponent,
    StoryTravellverNoteComponent,
    NotFoundComponent,
    ForbiddenErrorComponent,
    DifferenceYouMakeComponent,
    TravellerManifestoComponent
  ],
  imports: [CommonModule, MainRoutingModule, ThemeModule, SharedModule]
})
export class MainModule {}
